# Generated by Django 5.2.1 on 2025-06-03 16:11

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('imagen', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Imagen')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categoria',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Color')),
                ('codigo_hex', models.CharField(blank=True, max_length=7, null=True, verbose_name='Código HEX')),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colores',
                'db_table': 'color',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('imagen', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Imagen')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'db_table': 'marca',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Talla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Talla')),
            ],
            options={
                'verbose_name': 'Talla',
                'verbose_name_plural': 'Tallas',
                'db_table': 'talla',
            },
        ),
        migrations.CreateModel(
            name='CombinacionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU de Combinación')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tienda.color', verbose_name='Color')),
            ],
            options={
                'verbose_name': 'Combinación de Producto',
                'verbose_name_plural': 'Combinaciones de Producto',
                'db_table': 'combinacion_producto',
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('departamento', models.CharField(max_length=100, verbose_name='Departamento')),
                ('provincia', models.CharField(max_length=100, verbose_name='Provincia')),
                ('distrito', models.CharField(max_length=100, verbose_name='Distrito')),
                ('calle', models.CharField(max_length=255, verbose_name='Calle y número')),
                ('codigo_postal', models.CharField(max_length=20, verbose_name='Código Postal')),
                ('referencia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Referencia')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono de contacto')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Dirección',
                'verbose_name_plural': 'Direcciones',
                'db_table': 'direccion',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('metodo_pago', models.CharField(max_length=50, verbose_name='Método de Pago')),
                ('estado_pago', models.CharField(default='pendiente', max_length=30, verbose_name='Estado de Pago')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado de la Orden')),
                ('cantidad_compra', models.IntegerField(default=0, verbose_name='Cantidad de Productos')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('direccion_envio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Tienda.direccion', verbose_name='Dirección de Envío')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Órdenes',
                'db_table': 'orden',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='OrdenItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('combinacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Tienda.combinacionproducto', verbose_name='Combinación de Producto')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Tienda.orden', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Item de Orden',
                'verbose_name_plural': 'Items de Orden',
                'db_table': 'orden_item',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('precio_oferta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio en Oferta')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('es_destacado', models.BooleanField(default=False, verbose_name='Es Destacado')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tienda.categoria', verbose_name='Categoría')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tienda.marca', verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Imagen')),
                ('es_principal', models.BooleanField(default=False, verbose_name='¿Es imagen principal?')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='Tienda.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Imagen de Producto',
                'verbose_name_plural': 'Imágenes de Productos',
                'db_table': 'imagen_producto',
                'ordering': ['orden', 'creado'],
            },
        ),
        migrations.AddField(
            model_name='combinacionproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combinaciones', to='Tienda.producto', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='combinacionproducto',
            name='talla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tienda.talla', verbose_name='Talla'),
        ),
        migrations.AlterUniqueTogether(
            name='combinacionproducto',
            unique_together={('producto', 'talla', 'color')},
        ),
    ]
